title: Taming the BEAST Lectures
email:
description: 

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  -
    scope:
      path: ""
    values:
      layout: lecture
      reveal:
        theme: ../reveal.js/css/theme/white.css
        center: true
        controls: false
        progress: false
        history: false
        center: false
        mouseWheel: false
        slideNumber: false
        transition: none
